### ISSUE TITLE
get_fitbit_activities error

### ISSUE THREAD

**Issue by jclutton** [bhelsel/iFitbit#2]
`library(iFitbit)

fitbit_dir <- file.path(data_dir,'fitbit')
token_pathname <- file.path(fitbit_dir,'tokens','8Z9PYN.Rdata')

refresh_fitbit_token(
  token.pathname = token_pathname,
  key = FITBIT_KEY, 
  secret = FITBIT_SECRET,
  force.refresh = FALSE
)

get_fitbit_activities(token.pathname = token_pathname,
                      start.date = "2022-01-01")`

error: 
![image](https://user-images.githubusercontent.com/83718912/228409748-366c3b88-5384-478c-a816-a468336b8a3b.png)

**Comment by bhelsel** [comment]
@jclutton I have received a similar error and I don't think it's an issue with the `iFitbit` package. I'm wondering if Fitbit limits the number of activities or dates that can be pulled at a single time from their web API? I know that you can only make 150 daily API calls but haven't been able to find documentation on the number of activities that can be pulled with a single API call. 

Do you still get the error if you set the `end.date` argument to 30 days after the `start.date`? If that works, I can try to figure out the maximum limit and add a warning or error message to let the user know. Thanks for bringing up the issue!
